// @ts-nocheck
import { default as __fd_glob_73 } from "../content/docs/getting-started/meta.json?collection=meta"
import { default as __fd_glob_72 } from "../content/docs/icons/meta.json?collection=meta"
import { default as __fd_glob_71 } from "../content/docs/lib/meta.json?collection=meta"
import { default as __fd_glob_70 } from "../content/docs/hooks/meta.json?collection=meta"
import { default as __fd_glob_69 } from "../content/docs/components/meta.json?collection=meta"
import { default as __fd_glob_68 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_67 from "../content/docs/getting-started/what-is-rockin.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/getting-started/theming.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/getting-started/quick-start.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/lib/utils.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/lib/compose-refs.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/lib/capacitor.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/icons/lucide.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/icons/loader.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/icons/icon-swap.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/icons/gravity.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/icons/bell.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/hooks/use-search-params.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/hooks/use-native.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/hooks/use-mounted.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/hooks/use-media-query.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/hooks/use-isomorphic-layout-effect.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/components/top-loader.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/toaster.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/sortable.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/scroll-area.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/quantity.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/otp.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/native-app-bridge.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/message.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/message-scroller.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/label.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/kbd.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/jelly.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/item.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/input-otp.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/input-group.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/image.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/filters.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/field.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/empty.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/drawer.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/dock.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/dashed-separator.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/command.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/combobox.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/chart.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/carousel.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/button-group.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/bubble.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/autocomplete.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/apple-hello.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/components/animated-div.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/cn.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();

export const docs = await create.doc("docs", "content/docs", {"cn.mdx": __fd_glob_0, "index.mdx": __fd_glob_1, "components/accordion.mdx": __fd_glob_2, "components/alert-dialog.mdx": __fd_glob_3, "components/animated-div.mdx": __fd_glob_4, "components/apple-hello.mdx": __fd_glob_5, "components/autocomplete.mdx": __fd_glob_6, "components/avatar.mdx": __fd_glob_7, "components/badge.mdx": __fd_glob_8, "components/bubble.mdx": __fd_glob_9, "components/button-group.mdx": __fd_glob_10, "components/button.mdx": __fd_glob_11, "components/card.mdx": __fd_glob_12, "components/carousel.mdx": __fd_glob_13, "components/chart.mdx": __fd_glob_14, "components/checkbox.mdx": __fd_glob_15, "components/combobox.mdx": __fd_glob_16, "components/command.mdx": __fd_glob_17, "components/dashed-separator.mdx": __fd_glob_18, "components/dialog.mdx": __fd_glob_19, "components/dock.mdx": __fd_glob_20, "components/drawer.mdx": __fd_glob_21, "components/dropdown-menu.mdx": __fd_glob_22, "components/empty.mdx": __fd_glob_23, "components/field.mdx": __fd_glob_24, "components/filters.mdx": __fd_glob_25, "components/image.mdx": __fd_glob_26, "components/input-group.mdx": __fd_glob_27, "components/input-otp.mdx": __fd_glob_28, "components/input.mdx": __fd_glob_29, "components/item.mdx": __fd_glob_30, "components/jelly.mdx": __fd_glob_31, "components/kbd.mdx": __fd_glob_32, "components/label.mdx": __fd_glob_33, "components/message-scroller.mdx": __fd_glob_34, "components/message.mdx": __fd_glob_35, "components/native-app-bridge.mdx": __fd_glob_36, "components/otp.mdx": __fd_glob_37, "components/popover.mdx": __fd_glob_38, "components/quantity.mdx": __fd_glob_39, "components/radio-group.mdx": __fd_glob_40, "components/scroll-area.mdx": __fd_glob_41, "components/select.mdx": __fd_glob_42, "components/separator.mdx": __fd_glob_43, "components/skeleton.mdx": __fd_glob_44, "components/sortable.mdx": __fd_glob_45, "components/switch.mdx": __fd_glob_46, "components/textarea.mdx": __fd_glob_47, "components/toaster.mdx": __fd_glob_48, "components/tooltip.mdx": __fd_glob_49, "components/top-loader.mdx": __fd_glob_50, "hooks/use-isomorphic-layout-effect.mdx": __fd_glob_51, "hooks/use-media-query.mdx": __fd_glob_52, "hooks/use-mounted.mdx": __fd_glob_53, "hooks/use-native.mdx": __fd_glob_54, "hooks/use-search-params.mdx": __fd_glob_55, "icons/bell.mdx": __fd_glob_56, "icons/gravity.mdx": __fd_glob_57, "icons/icon-swap.mdx": __fd_glob_58, "icons/loader.mdx": __fd_glob_59, "icons/lucide.mdx": __fd_glob_60, "lib/capacitor.mdx": __fd_glob_61, "lib/compose-refs.mdx": __fd_glob_62, "lib/utils.mdx": __fd_glob_63, "getting-started/installation.mdx": __fd_glob_64, "getting-started/quick-start.mdx": __fd_glob_65, "getting-started/theming.mdx": __fd_glob_66, "getting-started/what-is-rockin.mdx": __fd_glob_67, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_68, "components/meta.json": __fd_glob_69, "hooks/meta.json": __fd_glob_70, "lib/meta.json": __fd_glob_71, "icons/meta.json": __fd_glob_72, "getting-started/meta.json": __fd_glob_73, });