/**
 * Extracts the source of each `export function XxxDemo()` in
 * components/previews/*.tsx into lib/preview-code.generated.ts so
 * ComponentPreview can show the code behind each demo.
 *
 * Run: bun scripts/generate-preview-code.ts
 */
import * as fs from "node:fs"
import * as path from "node:path"

const PREVIEWS_DIR = path.join(import.meta.dir, "../components/previews")
const OUT_FILE = path.join(import.meta.dir, "../lib/preview-code.generated.ts")

function toKebab(name: string): string {
  return name
    .replace(/Demo$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
}

const map: Record<string, string> = []

for (const file of fs.readdirSync(PREVIEWS_DIR).filter((f) => f.endsWith(".tsx")).sort()) {
  const source = fs.readFileSync(path.join(PREVIEWS_DIR, file), "utf8")
  // Match top-level `export function XxxDemo() {` and capture until the closing
  // brace at column 0.
  const re = /^export function ([A-Za-z0-9]+Demo)(?:\([^)]*\))? \{[^]*?\n\}/gm
  let match: RegExpExecArray | null
  while ((match = re.exec(source))) {
    const [, name] = match
    map.push([toKebab(name), source.slice(match.index, match.index + match[0].length)])
  }
}

const lines = [
  "// AUTO-GENERATED by scripts/generate-preview-code.ts — do not edit.",
  "export const previewCode: Record<string, string> = {",
  ...map.map(([key, code]) =>
    `  "${key}": ${JSON.stringify(code)},`
  ),
  "}",
  "",
]

fs.writeFileSync(OUT_FILE, lines.join("\n"))
console.log(`Wrote ${map.length} preview sources -> ${path.relative(process.cwd(), OUT_FILE)}`)
for (const [key] of map) console.log("  ", key)
